# docker-compose.yml
# 用于本地开发和测试的Docker Compose配置

version: '3.8'

services:
  shenlun-backend:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - LOG_LEVEL=INFO
      - MAX_CONCURRENT_REQUESTS=20
      - RATE_LIMIT_PER_MINUTE=100
      - ENABLE_RESPONSE_CACHE=true
      - CACHE_TTL_SECONDS=300
      - HEALTH_CHECK_ENABLED=true
      - SERVER_ID=docker-backend-1
    volumes:
      - ./knowledge_base_data:/app/knowledge_base_data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加负载均衡器(nginx)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - shenlun-backend
    restart: unless-stopped
    profiles:
      - load-balancer

volumes:
  knowledge_base_data:
  logs:

networks:
  default:
    name: shenlun-network